# Generated by Django 3.2.5 on 2021-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
