# Generated by Django 3.2.5 on 2021-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
