# Generated by Django 3.2.5 on 2021-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='before_menu_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page_name',
            field=models.CharField(max_length=255),
        ),
    ]
