# Generated by Django 3.2.5 on 2021-08-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
        ('menus', '0004_menuhaspermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuhaspermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='menuhaspermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_user.permission'),
        ),
    ]
