# Generated by Django 3.2.5 on 2021-08-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_pic_url'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchhasgoods',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodsdiscount'),
        ),
    ]
