# Generated by Django 3.2.5 on 2021-08-09 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0001_initial'),
        ('branch', '0001_initial'),
        ('goods', '0001_initial'),
        ('supplier', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('name', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
                ('all_num', models.IntegerField()),
                ('all_price', models.FloatField()),
                ('real_price', models.FloatField()),
                ('state', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField(default=1)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_user.adminuser')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('number', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('is_deal', models.IntegerField(default=0)),
                ('node', models.TextField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodshassku')),
            ],
        ),
        migrations.CreateModel(
            name='UndonePurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('number', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField(default=1)),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodshassku')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('flag', models.IntegerField(default=1)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_user.adminuser')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.saleorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('flag', models.IntegerField(default=1)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_user.adminuser')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.IntegerField()),
                ('get_number', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField(default=1)),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodshassku')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.purchaseorder')),
            ],
        ),
    ]
